### ISSUE TITLE
Issues in Edit Mode

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#428]
I can turn all of these into individual issues, but wanted to capture them as I go through. All tests in Chrome on OS X.

All editors

- [x]  jwt expired - expired login does not auto-logout, all changes lost and redirected to homepage on logout/login
- [x]  Tags autocomplete not populated (nothing in console)
- [x]  Related cases and related methods autocomplete not populated (nothing in console)
- [x]  Related organizations autocomplete populated, but has a bug when you try to select one. In material-ui-chip-input it was calling `.trim()` on an object, rather than the `.text` of that object. This appears to be a bug in the material-ui-chip-input, but may be because we are passing in a list of objects rather than a list of strings. (see stacktrace below)
- [x]  Still appears to be sending existing data to API server, not user-input data (tried changing `Voting` in Case, `Communication mode` in Method.
- [x]  Order of fields is different in edit vs. view, which is confusing
- [x]  Existing field value not visible in edit view

Case

Tested on https://participedia.xyz/case/4558/edit

- [x] `Keyword` autocomplete not responding as an input at all (nothing in console)
- [x]  `End date` is not blank or populated with a date after the start date, but with the epoch and you have to go through the widget month by month from 1970 to get a valid date.
- [x]  `Number of Meeting Days` and `Total number of participants` allow text entry, don't restrict to numbers
- [x]  `Staff type` dropdown appears to only have one entry: `organizers`, only appears after double-click on the input field.
- [x]  `Who else supported the initiative` dropdown appears to have only one entry: `YouGov`, only appears after double-click on the input field.

Method

Tested on https://participedia.xyz/method/4313/edit

- [x] `Communication Mode` unchanged after submitting a change

Organization

- [x] Not showing all editable fields e.g. `specific_topic` in organization ID 4480

Stacktrace for material-ui-chip-input bug:

```
Uncaught TypeError: chip.trim is not a function
    at ChipInput.handleAddChip (http://localhost:3000/static/js/bundle.js:140829:18)
    at Object.autoComplete.handleItemTouchTap [as onItemTouchTap] (http://localhost:3000/static/js/bundle.js:140733:16)
    at Menu.handleMenuItemTouchTap (http://localhost:3000/static/js/bundle.js:44802:18)
    at Object.onTouchTap (http://localhost:3000/static/js/bundle.js:44704:20)
    at EnhancedButton._this.handleTouchTap (http://localhost:3000/static/js/bundle.js:19200:21)
    at Object.ReactErrorUtils.invokeGuardedCallback (http://localhost:3000/static/js/bundle.js:57579:16)
    at executeDispatch (http://localhost:3000/static/js/bundle.js:45974:21)
    at Object.executeDispatchesInOrder (http://localhost:3000/static/js/bundle.js:45997:5)
    at executeDispatchesAndRelease (http://localhost:3000/static/js/bundle.js:19507:22)
    at executeDispatchesAndReleaseTopLevel (http://localhost:3000/static/js/bundle.js:19518:10)
    at Array.forEach (native)
    at forEachAccumulated (http://localhost:3000/static/js/bundle.js:83385:9)
    at Object.processEventQueue (http://localhost:3000/static/js/bundle.js:19721:7)
    at runEventQueueInBatch (http://localhost:3000/static/js/bundle.js:161726:18)
    at Object.handleTopLevel [as _handleTopLevel] (http://localhost:3000/static/js/bundle.js:161737:5)
    at handleTopLevelImpl (http://localhost:3000/static/js/bundle.js:161824:24)
    at ReactDefaultBatchingStrategyTransaction.perform (http://localhost:3000/static/js/bundle.js:46347:20)
    at Object.batchedUpdates (http://localhost:3000/static/js/bundle.js:62700:26)
    at Object.batchedUpdates (http://localhost:3000/static/js/bundle.js:11910:27)
    at dispatchEvent (http://localhost:3000/static/js/bundle.js:161899:20)
handleAddChip @ ChipInput.js:401
autoComplete.handleItemTouchTap @ ChipInput.js:305
handleMenuItemTouchTap @ Menu.js:336
onTouchTap @ Menu.js:238
EnhancedButton._this.handleTouchTap @ EnhancedButton.js:153
ReactErrorUtils.invokeGuardedCallback @ ReactErrorUtils.js:69
executeDispatch @ EventPluginUtils.js:85
executeDispatchesInOrder @ EventPluginUtils.js:108
executeDispatchesAndRelease @ EventPluginHub.js:43
executeDispatchesAndReleaseTopLevel @ EventPluginHub.js:54
forEachAccumulated @ forEachAccumulated.js:24
processEventQueue @ EventPluginHub.js:257
runEventQueueInBatch @ ReactEventEmitterMixin.js:17
handleTopLevel @ ReactEventEmitterMixin.js:28
handleTopLevelImpl @ ReactEventListener.js:72
perform @ Transaction.js:140
batchedUpdates @ ReactDefaultBatchingStrategy.js:62
batchedUpdates @ ReactUpdates.js:97
dispatchEvent @ ReactEventListener.js:147
```

**Comment by andreadelrio** [comment]
Got this when trying to select a related case from MethodEditor 

![image](https://user-images.githubusercontent.com/4016496/27007435-7226b720-4e08-11e7-8c43-7159a43cc6b8.png)

**Comment by andreadelrio** [comment]
`MethodEditor`

- [ ] `Facilitated` radius button not working
- [ ] `method_of_interaction` is duplicated

**Comment by davidascher** [comment]
nice.  fixed all three in https://github.com/participedia/frontend/pull/446

**Comment by andreadelrio** [comment]
`OrganizationEditor` 
- Missing `specific_topic` (`issue`) field
- Should we removed the "keywords" sections and just keep "tags"?

**Comment by andreadelrio** [comment]
Checking the database, organizations have `executive_director` and `sector` fields. Not sure if you want to include those in their edit page?

**Comment by davidascher** [comment]
Totally, and coming up!

**Comment by davidascher** [comment]
I'm going to close this issue as I believe I've dealt with all of these.  Great QA, let's do more.  Please use the checkbox for each buglet, so i can track each of them. thx!
