### ISSUE TITLE
Improvements to editors

### ISSUE THREAD

**Issue by andreadelrio** [participedia/frontend#464]
`CaseEditor`
https://participedia.xyz/case/4558/edit

- [ ] Capitalize all fields (e.g. `voting`)
- [ ] Don't show word 'null' in `Number of meeting days`
- [ ] Getting error 401 `in isUser, user doesn't have Contributors group membership` when trying to upload a pic.

**Comment by davidascher** [comment]
On the third: I think that Contributors membership test is obsolete.  See https://github.com/participedia/api/issues/142 for the source of the bug.

**Comment by davidascher** [comment]
@andreadelrio in the meantime i've added you to the Contributors group, so you should be able to upload a pic.

**Comment by davidascher** [comment]
using the andrea @ mail login

**Comment by andreadelrio** [comment]
@davidascher Still getting the same error when trying to upload a pic, do I need to do anything on my side?

**Comment by davidascher** [comment]
sign out and sign back in?

**Comment by andreadelrio** [comment]
Can upload. Getting the following when trying to save Case with new pics.
```Possibly Unhandled Rejection at: Promise  Promise {
  <rejected> ReferenceError: att is not defined
    at ARRAY[.atts.map.vid (/Users/andrea_delrio/projects/api/api/helpers/db.js:70:23)
    at Array.map (native)
    at Object.attachments (/Users/andrea_delrio/projects/api/api/helpers/db.js:67:10)
    at Object.keys.forEach (/Users/andrea_delrio/projects/api/api/helpers/things.js:228:25)
    at Array.forEach (native)
    at editById (/Users/andrea_delrio/projects/api/api/helpers/things.js:138:29) }  reason:  ReferenceError: att is not defined
    at ARRAY[.atts.map.vid (/Users/andrea_delrio/projects/api/api/helpers/db.js:70:23)
    at Array.map (native)
    at Object.attachments (/Users/andrea_delrio/projects/api/api/helpers/db.js:67:10)
    at Object.keys.forEach (/Users/andrea_delrio/projects/api/api/helpers/things.js:228:25)
    at Array.forEach (native)
    at editById (/Users/andrea_delrio/projects/api/api/helpers/things.js:138:29)```

**Comment by davidascher** [comment]
Can you see if the fix in https://github.com/participedia/api/pull/143 fixes it?

**Comment by davidascher** [comment]
it's just `vid` -> `att`

**Comment by andreadelrio** [comment]
Yes, will check

**Comment by andreadelrio** [comment]
```error: Exception in PUT /case/4562 => error: syntax error at or near ")"
Trace: { error: syntax error at or near ")"
    at Connection.parseE (/Users/andrea_delrio/projects/api/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/andrea_delrio/projects/api/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/andrea_delrio/projects/api/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
  name: 'error',
  length: 83,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '46',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1081',
  routine: 'scanner_yyerror' }
    at editById (/Users/andrea_delrio/projects/api/api/helpers/things.js:286:15)
PUT /case/4562 500 49.436 ms - 157

**Comment by davidascher** [comment]
ugh. that's painful.

next step is to turn on SQL logging in the API server, see what SQL command is being tried.

Can you stop the api server, set `LOG_QUERY=true` and restart the api server? you should see some SQL logs when you try again.

we'll probably need @dethe to take a look.

**Comment by dethe** [comment]
Oh, cool! I'll take a look. When I wrote the image ingestion the client wasn't sending images, now I can match it to reality.

**Comment by andreadelrio** [comment]
```OPTIONS /case/4563 204 0.187 ms - -
Executing query SELECT id FROM users WHERE email = 'andrea@mail.com' ;
Executing query WITH authors_list AS ( SELECT array_agg(( authors.user_id, authors.timestamp, users.name )::author) authors FROM authors, users WHERE authors.user_id = users.id AND authors.thingid = '4563' ), full_thing AS ( SELECT "cases".*, COALESCE("cases".other_images, '{}') other_images, COALESCE("cases".files, '{}') files, COALESCE("cases".videos, '{}') videos, COALESCE("cases".tags, '{}') tags, COALESCE("cases".links, '{}') links, localized_texts.body, localized_texts.title, authors_list.authors, get_related_nouns('case', 'case', '4563', 'en' ) AS related_cases, get_related_nouns('method', 'case', '4563', 'en' ) AS related_methods, get_related_nouns('organization', 'case', '4563', 'en' ) AS related_organizations, bookmarked("cases".type, '4563', 224984) FROM "cases", localized_texts, authors_list WHERE "cases".id = localized_texts.thingid AND localized_texts.language = 'en' AND "cases".id = '4563' ) SELECT to_json(full_thing.*) results FROM full_thing ;
Executing query UPDATE cases SET "other_images" = ARRAY['NaN'), 'NaN')]::attachment[], updated_date = 'now' WHERE id = '4563' ;
error: Exception in PUT /case/4563 => error: syntax error at or near ")"
Trace: { error: syntax error at or near ")"
    at Connection.parseE (/Users/andrea_delrio/projects/api/node_modules/pg/lib/connection.js:539:11)
    at Connection.parseMessage (/Users/andrea_delrio/projects/api/node_modules/pg/lib/connection.js:366:17)
    at Socket.<anonymous> (/Users/andrea_delrio/projects/api/node_modules/pg/lib/connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
  name: 'error',
  length: 83,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '46',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1081',
  routine: 'scanner_yyerror' }
    at editById (/Users/andrea_delrio/projects/api/api/helpers/things.js:286:15)
PUT /case/4563 500 44.239 ms - 157

**Comment by davidascher** [comment]
@andreadelrio can you break this issue into however many are still happening for you? thx.
